In [4]:
# Importaci√≥n de librerias
import pandas as pd
import ast
import gzip
from datetime import datetime
import gzip

In [6]:
# Carga del dataframe con el archivo steam_games.json.gz
df_steam_games = pd.read_json('dataset/steam_games.json.gz',lines=True,compression='gzip')
df_steam_games.head(10)

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
0,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
1,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
2,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
3,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
4,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
5,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
6,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
7,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
8,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None
9,None,None,None,None,None,None,None,None,None,None,NaN,NaN,None

In [116]:
# Revisamos la estructura de la data
df_steam_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120445 entries, 0 to 120444
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publisher     24083 non-null  object
 1   genres        28852 non-null  object
 2   app_name      32133 non-null  object
 3   title         30085 non-null  object
 4   url           32135 non-null  object
 5   release_date  30068 non-null  object
 6   tags          31972 non-null  object
 7   reviews_url   32133 non-null  object
 8   specs         31465 non-null  object
 9   price         30758 non-null  object
 10  early_access  32135 non-null  float64
 11  id            32133 non-null  float64
 12  developer     28836 non-null  object
dtypes: float64(2), object(11)
memory usage: 11.9+ MB

In [117]:
# Eliminar filas donde todos los valores son NaN
df_steam_games_clean = df_steam_games.dropna(how='all')
df_steam_games_clean

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
88310,Kotoshiro,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,2018-01-04,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,0.0,761140.0,Kotoshiro
88311,"Making Fun, Inc.","[Free to Play, Indie, RPG, Strategy]",Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,2018-01-04,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free To Play,0.0,643980.0,Secret Level SRL
88312,Poolians.com,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,2017-07-24,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",Free to Play,0.0,670290.0,Poolians.com
88313,ÂΩºÂ≤∏È¢ÜÂüü,"[Action, Adventure, Casual]",ÂºπÁÇ∏‰∫∫2222,ÂºπÁÇ∏‰∫∫2222,http://store.steampowered.com/app/767400/2222/,2017-12-07,"[Action, Adventure, Casual]",http://steamcommunity.com/app/767400/reviews/?...,[Single-player],0.99,0.0,767400.0,ÂΩºÂ≤∏È¢ÜÂüü
88314,None,None,Log Challenge,None,http://store.steampowered.com/app/773570/Log_C...,None,"[Action, Indie, Casual, Sports]",http://steamcommunity.com/app/773570/reviews/?...,"[Single-player, Full controller support, HTC V...",2.99,0.0,773570.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,"[Single-player, Steam Achievements]",1.99,0.0,773640.0,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,"[Single-player, Steam Achievements, Steam Clou...",4.99,0.0,733530.0,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,0.0,610660.0,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,0.0,658870.0,"xropi,stev3ns"
120444,None,None,Maze Run VR,None,http://store.steampowered.com/app/681550/Maze_...,None,"[Early Access, Adventure, Indie, Action, Simul...",http://steamcommunity.com/app/681550/reviews/?...,"[Single-player, Stats, Steam Leaderboards, HTC...",4.99,1.0,681550.0,None

In [118]:
# Mostrmos la columnas de la data
df_steam_games.columns

Index(['publisher', 'genres', 'app_name', 'title', 'url', 'release_date',
       'tags', 'reviews_url', 'specs', 'price', 'early_access', 'id',
       'developer'],
      dtype='object')

In [119]:
# Eliminamos las columnas que no requerimos 
df_steam_games.drop(columns=['publisher',  'app_name', 'title', 'url',  'tags', 'reviews_url', 'specs', 'price', 'developer'], inplace=True)
df_steam_games

,genres,release_date,early_access,id
0,None,None,NaN,NaN
1,None,None,NaN,NaN
2,None,None,NaN,NaN
3,None,None,NaN,NaN
4,None,None,NaN,NaN
...,...,...,...,...
120440,"[Casual, Indie, Simulation, Strategy]",2018-01-04,0.0,773640.0
120441,"[Casual, Indie, Strategy]",2018-01-04,0.0,733530.0
120442,"[Indie, Racing, Simulation]",2018-01-04,0.0,610660.0
120443,"[Casual, Indie]",2017-09-02,0.0,658870.0
120444,None,None,1.0,681550.0

In [120]:
# la lista de generos se acomoda en filas unicas para cada tipo
df_steam_games = df_steam_games.explode('genres')
df_steam_games.head(3)

  genres release_date  early_access  id
0   None         None           NaN NaN
1   None         None           NaN NaN
2   None         None           NaN NaN

In [121]:
# Se procede a eliminar todas las filas en donde todos los valores sean NaN y observamos los resultados
df_steam_games = df_steam_games.dropna(how='all')

print('N√∫mero de filas por columnas: ', df_steam_games.shape)
df_steam_games.info()
df_steam_games.head()
df_steam_games.shape

N√∫mero de filas por columnas:  (74837, 4)
<class 'pandas.core.frame.DataFrame'>
Index: 74837 entries, 88310 to 120444
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   genres        71554 non-null  object
 1   release_date  72735 non-null  object
 2   early_access  74837 non-null  float64
 3   id            74834 non-null  float64
dtypes: float64(2), object(2)
memory usage: 2.9+ MB

(74837, 4)

In [122]:
# Relacionar la cantidad de valores NaN por cada Etiqueta
df_steam_games.isna().sum()

genres          3283
release_date    2102
early_access       0
id                 3
dtype: int64

In [123]:
# Verificar duplicados
tiene_duplicados = df_steam_games['id'].duplicated().any()
duplicados = df_steam_games[df_steam_games['id'].duplicated()]['id']
print(duplicados)

88310     761140.0
88310     761140.0
88310     761140.0
88310     761140.0
88311     643980.0
            ...
120441    733530.0
120441    733530.0
120442    610660.0
120442    610660.0
120443    658870.0
Name: id, Length: 42704, dtype: float64

In [124]:
# Al ver 59104 duplicados se procede a eliminar 
df_items = df_steam_games.drop_duplicates(keep='first')
df_items

            genres release_date  early_access        id
88310       Action   2018-01-04           0.0  761140.0
88310       Casual   2018-01-04           0.0  761140.0
88310        Indie   2018-01-04           0.0  761140.0
88310   Simulation   2018-01-04           0.0  761140.0
88310     Strategy   2018-01-04           0.0  761140.0
...            ...          ...           ...       ...
120442      Racing   2018-01-04           0.0  610660.0
120442  Simulation   2018-01-04           0.0  610660.0
120443      Casual   2017-09-02           0.0  658870.0
120443       Indie   2017-09-02           0.0  658870.0
120444        None         None           1.0  681550.0

[74836 rows x 4 columns]

In [125]:
# revisamos el data
df_items.head()

           genres release_date  early_access        id
88310      Action   2018-01-04           0.0  761140.0
88310      Casual   2018-01-04           0.0  761140.0
88310       Indie   2018-01-04           0.0  761140.0
88310  Simulation   2018-01-04           0.0  761140.0
88310    Strategy   2018-01-04           0.0  761140.0

In [126]:
# Verificar duplicados
tiene_duplicados = df_items['id'].duplicated().any()
duplicados = df_items[df_items['id'].duplicated()]['id']
print(duplicados)

88310     761140.0
88310     761140.0
88310     761140.0
88310     761140.0
88311     643980.0
            ...
120441    733530.0
120441    733530.0
120442    610660.0
120442    610660.0
120443    658870.0
Name: id, Length: 42703, dtype: float64

In [127]:
# Revisar la columna release_date si tiene valore nulos
print(df_items['release_date'].isna().sum())
#print(df_steam_games['release_date'].isna())
df_items.isna().sum()

2102

genres          3283
release_date    2102
early_access       0
id                 3
dtype: int64

In [128]:
df_users_items_clean = df_items.dropna(subset=['release_date'])

In [129]:
""" 
   Se decide transformar la columna release_date con el valor de a√±o, pero hay que tener en cuenta que tiene valores (2066 valores nulos) y el formato 
   actual no es de tipo date, para el caso de valores nulos, se contemplan los criterios como que los nulos tienen una distribuci√≥n aleatorios y 
   no tiene otras  columnas relacionadas; se  opta con actualziar los nulos con la mediana de las fechas. """

# Convertir la columna release_date a datetime
df_items['release_date'] = pd.to_datetime(df_items['release_date'], errors='coerce')

# Calcular la mediana de las fechas
# Convertir las fechas a enteros de 64 bits para calcular la mediana
median_timestamp = df_items['release_date'].dropna().astype('int64').median()
median_date = pd.to_datetime(median_timestamp)

# Rellenar los valores nulos con la mediana de fechas
df_items['release_date'] = df_items['release_date'].fillna(median_date)

C:\Users\juank\AppData\Local\Temp\ipykernel_15024\190645669.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_items['release_date'] = pd.to_datetime(df_items['release_date'], errors='coerce')
C:\Users\juank\AppData\Local\Temp\ipykernel_15024\190645669.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_items['release_date'] = df_items['release_date'].fillna(median_date)

In [130]:
# Asegurando que la columna release_date est√© con formato date, se procede a lo siguiente:
# Adicionar una columna 'year' que extrae el a√±o de la columna 'release_date'
df_items['year'] = df_items['release_date'].dt.year

C:\Users\juank\AppData\Local\Temp\ipykernel_15024\3102263667.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_items['year'] = df_items['release_date'].dt.year

In [131]:
# Convertir la columna 'release_date' a datetime
df_items['release_date'] = pd.to_datetime(df_items['release_date'])

# Extraer el a√±o y asignarlo a una nueva columna 'year'
df_items['year'] = df_items['release_date'].dt.year

C:\Users\juank\AppData\Local\Temp\ipykernel_15024\3717460012.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_items['release_date'] = pd.to_datetime(df_items['release_date'])
C:\Users\juank\AppData\Local\Temp\ipykernel_15024\3717460012.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_items['year'] = df_items['release_date'].dt.year

In [132]:
# Revisamos la data
df_items.head()

           genres release_date  early_access        id  year
88310      Action   2018-01-04           0.0  761140.0  2018
88310      Casual   2018-01-04           0.0  761140.0  2018
88310       Indie   2018-01-04           0.0  761140.0  2018
88310  Simulation   2018-01-04           0.0  761140.0  2018
88310    Strategy   2018-01-04           0.0  761140.0  2018

In [133]:
# Eliminamos la columna release_date
df_items.drop(columns=['release_date'], inplace=True)

C:\Users\juank\AppData\Local\Temp\ipykernel_15024\84409770.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_items.drop(columns=['release_date'], inplace=True)

In [134]:
# Revisamos la data
df_items_reviews = df_items.copy()

df_items_reviews

            genres  early_access        id  year
88310       Action           0.0  761140.0  2018
88310       Casual           0.0  761140.0  2018
88310        Indie           0.0  761140.0  2018
88310   Simulation           0.0  761140.0  2018
88310     Strategy           0.0  761140.0  2018
...            ...           ...       ...   ...
120442      Racing           0.0  610660.0  2018
120442  Simulation           0.0  610660.0  2018
120443      Casual           0.0  658870.0  2017
120443       Indie           0.0  658870.0  2017
120444        None           1.0  681550.0  2016

[74836 rows x 4 columns]

In [135]:
# revisemos columnas
df_items_reviews.columns

Index(['genres', 'early_access', 'id', 'year'], dtype='object')

In [7]:
# Carga del dataframe con el archivo users_items.json.gz
data = []
with gzip.open('dataset/users_items.json.gz', 'rt', encoding='utf-8') as file:
    for line in file:
        try:
            json_data = ast.literal_eval(line)
            data.append(json_data)
        except ValueError as e:
            print(f"Error en la l√≠nea: {line}")
            continue
df_users_items = pd.DataFrame(data)

df_users_items

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."
...,...,...,...,...,...
88305,76561198323066619,22,76561198323066619,http://steamcommunity.com/profiles/76561198323...,"[{'item_id': '413850', 'item_name': 'CS:GO Pla..."
88306,76561198326700687,177,76561198326700687,http://steamcommunity.com/profiles/76561198326...,"[{'item_id': '11020', 'item_name': 'TrackMania..."
88307,XxLaughingJackClown77xX,0,76561198328759259,http://steamcommunity.com/id/XxLaughingJackClo...,[]
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"[{'item_id': '304930', 'item_name': 'Unturned'..."
88309,edward_tremethick,0,76561198331598578,http://steamcommunity.com/id/edward_tremethick,[]

In [54]:
# Revisamos las columnas de la data
df_users_items.columns

Index(['user_id', 'items_count', 'steam_id', 'user_url', 'items'], dtype='object')

In [55]:
# Solo requerimos las columnas usser_id y items
df_users_items.drop(columns=['items_count', 'steam_id', 'user_url'], inplace=True)

In [56]:
df_users_items

,user_id,items
0,76561197970982479,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."
...,...,...
88305,76561198323066619,"[{'item_id': '413850', 'item_name': 'CS:GO Pla..."
88306,76561198326700687,"[{'item_id': '11020', 'item_name': 'TrackMania..."
88307,XxLaughingJackClown77xX,[]
88308,76561198329548331,"[{'item_id': '304930', 'item_name': 'Unturned'..."
88309,edward_tremethick,[]

In [57]:
first_row_items = df_users_items.at[0, 'items']

# Mostrar el diccionario
print("\nDiccionario en la columna 'items' de la primera fila:")
first_row_items

Diccionario en la columna 'items' de la primera fila:

[{'item_id': '10',
  'item_name': 'Counter-Strike',
  'playtime_forever': 6,
  'playtime_2weeks': 0},
 {'item_id': '20',
  'item_name': 'Team Fortress Classic',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '30',
  'item_name': 'Day of Defeat',
  'playtime_forever': 7,
  'playtime_2weeks': 0},
 {'item_id': '40',
  'item_name': 'Deathmatch Classic',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '50',
  'item_name': 'Half-Life: Opposing Force',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '60',
  'item_name': 'Ricochet',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '70',
  'item_name': 'Half-Life',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '130',
  'item_name': 'Half-Life: Blue Shift',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '300',
  'item_name': 'Day of Defeat: Source',
  'playtime_forever': 4733,
  'playtime_2weeks': 0},
 {'item_id': '240',
  'item_name': 'Counter-Strike: Source',
  'playtime_forever': 1853,
  'playtime_2weeks': 0},
 {'item_id': '3830',
  'item_name': 'Psychonauts',
  'playtime_forever': 333,
  'playtime_2weeks': 0},
 {'item_id': '2630',
  'item_name': 'Call of Duty 2',
  'playtime_forever': 75,
  'playtime_2weeks': 0},
 {'item_id': '3900',
  'item_name': "Sid Meier's Civilization IV",
  'playtime_forever': 338,
  'playtime_2weeks': 0},
 {'item_id': '34440',
  'item_name': "Sid Meier's Civilization IV",
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '3920',
  'item_name': "Sid Meier's Pirates!",
  'playtime_forever': 2,
  'playtime_2weeks': 0},
 {'item_id': '6400',
  'item_name': 'Joint Task Force',
  'playtime_forever': 286,
  'playtime_2weeks': 0},
 {'item_id': '6910',
  'item_name': 'Deus Ex: Game of the Year Edition',
  'playtime_forever': 2685,
  'playtime_2weeks': 0},
 {'item_id': '7670',
  'item_name': 'BioShock',
  'playtime_forever': 633,
  'playtime_2weeks': 0},
 {'item_id': '409710',
  'item_name': 'BioShock Remastered',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '220',
  'item_name': 'Half-Life 2',
  'playtime_forever': 696,
  'playtime_2weeks': 0},
 {'item_id': '320',
  'item_name': 'Half-Life 2: Deathmatch',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '340',
  'item_name': 'Half-Life 2: Lost Coast',
  'playtime_forever': 37,
  'playtime_2weeks': 0},
 {'item_id': '360',
  'item_name': 'Half-Life Deathmatch: Source',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '380',
  'item_name': 'Half-Life 2: Episode One',
  'playtime_forever': 168,
  'playtime_2weeks': 0},
 {'item_id': '400',
  'item_name': 'Portal',
  'playtime_forever': 173,
  'playtime_2weeks': 0},
 {'item_id': '420',
  'item_name': 'Half-Life 2: Episode Two',
  'playtime_forever': 323,
  'playtime_2weeks': 0},
 {'item_id': '9340',
  'item_name': 'Company of Heroes: Opposing Fronts',
  'playtime_forever': 692,
  'playtime_2weeks': 0},
 {'item_id': '228200',
  'item_name': 'Company of Heroes (New Steam Version)',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '11450',
  'item_name': 'Overlord',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '7940',
  'item_name': 'Call of Duty 4: Modern Warfare',
  'playtime_forever': 1185,
  'playtime_2weeks': 0},
 {'item_id': '4700',
  'item_name': 'Medieval II: Total War',
  'playtime_forever': 477,
  'playtime_2weeks': 0},
 {'item_id': '12900',
  'item_name': 'Audiosurf',
  'playtime_forever': 115,
  'playtime_2weeks': 0},
 {'item_id': '13250',
  'item_name': 'Unreal Gold',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '16100',
  'item_name': 'Virtual Villagers: A New Home',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '15700',
  'item_name': "Oddworld: Abe's Oddysee",
  'playtime_forever': 28,
  'playtime_2weeks': 0},
 {'item_id': '15710',
  'item_name': "Oddworld: Abe's Exoddus",
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '17330',
  'item_name': 'Crysis Warhead',
  'playtime_forever': 31,
  'playtime_2weeks': 0},
 {'item_id': '17340',
  'item_name': 'Crysis Wars',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '22000',
  'item_name': 'World of Goo',
  'playtime_forever': 195,
  'playtime_2weeks': 0},
 {'item_id': '500',
  'item_name': 'Left 4 Dead',
  'playtime_forever': 513,
  'playtime_2weeks': 0},
 {'item_id': '4560',
  'item_name': 'Company of Heroes',
  'playtime_forever': 1061,
  'playtime_2weeks': 0},
 {'item_id': '17460',
  'item_name': 'Mass Effect',
  'playtime_forever': 1613,
  'playtime_2weeks': 0},
 {'item_id': '10500',
  'item_name': 'Empire: Total War',
  'playtime_forever': 186,
  'playtime_2weeks': 0},
 {'item_id': '24740',
  'item_name': 'Burnout Paradise: The Ultimate Box',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '22200',
  'item_name': 'Zeno Clash',
  'playtime_forever': 271,
  'playtime_2weeks': 0},
 {'item_id': '26800',
  'item_name': 'Braid',
  'playtime_forever': 445,
  'playtime_2weeks': 0},
 {'item_id': '1250',
  'item_name': 'Killing Floor',
  'playtime_forever': 10006,
  'playtime_2weeks': 0},
 {'item_id': '35420',
  'item_name': 'Killing Floor Mod: Defence Alliance 2',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '3590',
  'item_name': 'Plants vs. Zombies: Game of the Year',
  'playtime_forever': 4413,
  'playtime_2weeks': 0},
 {'item_id': '8880',
  'item_name': 'Freedom Force',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '8890',
  'item_name': 'Freedom Force vs. the 3rd Reich',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '23120',
  'item_name': 'Droplitz',
  'playtime_forever': 53,
  'playtime_2weeks': 0},
 {'item_id': '35700',
  'item_name': 'Trine',
  'playtime_forever': 199,
  'playtime_2weeks': 0},
 {'item_id': '10140',
  'item_name': '3D Ultra Minigolf Adventures Deluxe',
  'playtime_forever': 25,
  'playtime_2weeks': 0},
 {'item_id': '35010',
  'item_name': 'Batman: Arkham Asylum',
  'playtime_forever': 570,
  'playtime_2weeks': 0},
 {'item_id': '35140',
  'item_name': 'Batman: Arkham Asylum GOTY Edition',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '29180',
  'item_name': 'Osmos',
  'playtime_forever': 940,
  'playtime_2weeks': 0},
 {'item_id': '15520',
  'item_name': 'AaAaAA!!! - A Reckless Disregard for Gravity',
  'playtime_forever': 110,
  'playtime_2weeks': 0},
 {'item_id': '32370',
  'item_name': 'STAR WARS‚Ñ¢: Knights of the Old Republic‚Ñ¢',
  'playtime_forever': 5,
  'playtime_2weeks': 0},
 {'item_id': '37700',
  'item_name': 'Darkest of Days',
  'playtime_forever': 782,
  'playtime_2weeks': 0},
 {'item_id': '6020',
  'item_name': 'STAR WARS‚Ñ¢ Jedi Knight: Jedi Academy‚Ñ¢',
  'playtime_forever': 77,
  'playtime_2weeks': 0},
 {'item_id': '24860',
  'item_name': 'Battlefield 2',
  'playtime_forever': 437,
  'playtime_2weeks': 0},
 {'item_id': '39530',
  'item_name': 'Painkiller: Black Edition',
  'playtime_forever': 503,
  'playtime_2weeks': 0},
 {'item_id': '550',
  'item_name': 'Left 4 Dead 2',
  'playtime_forever': 1474,
  'playtime_2weeks': 0},
 {'item_id': '223530',
  'item_name': 'Left 4 Dead 2 Beta',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '8980',
  'item_name': 'Borderlands',
  'playtime_forever': 3061,
  'playtime_2weeks': 0},
 {'item_id': '41500',
  'item_name': 'Torchlight',
  'playtime_forever': 536,
  'playtime_2weeks': 0},
 {'item_id': '20900',
  'item_name': 'The Witcher: Enhanced Edition',
  'playtime_forever': 139,
  'playtime_2weeks': 0},
 {'item_id': '10180',
  'item_name': 'Call of Duty: Modern Warfare 2',
  'playtime_forever': 1886,
  'playtime_2weeks': 0},
 {'item_id': '10190',
  'item_name': 'Call of Duty: Modern Warfare 2 - Multiplayer',
  'playtime_forever': 1784,
  'playtime_2weeks': 0},
 {'item_id': '17450',
  'item_name': 'Dragon Age: Origins',
  'playtime_forever': 4431,
  'playtime_2weeks': 0},
 {'item_id': '3170',
  'item_name': "King's Bounty: Armored Princess",
  'playtime_forever': 1021,
  'playtime_2weeks': 0},
 {'item_id': '25900',
  'item_name': "King's Bounty: The Legend",
  'playtime_forever': 1389,
  'playtime_2weeks': 0},
 {'item_id': '31410',
  'item_name': 'Zombie Driver',
  'playtime_forever': 95,
  'playtime_2weeks': 0},
 {'item_id': '24980',
  'item_name': 'Mass Effect 2',
  'playtime_forever': 5001,
  'playtime_2weeks': 0},
 {'item_id': '8850',
  'item_name': 'BioShock 2',
  'playtime_forever': 1504,
  'playtime_2weeks': 0},
 {'item_id': '409720',
  'item_name': 'BioShock 2 Remastered',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '46000',
  'item_name': 'Bob Came in Pieces',
  'playtime_forever': 11,
  'playtime_2weeks': 0},
 {'item_id': '33230',
  'item_name': "Assassin's Creed II",
  'playtime_forever': 1636,
  'playtime_2weeks': 0},
 {'item_id': '20820',
  'item_name': 'Shatter',
  'playtime_forever': 46,
  'playtime_2weeks': 0},
 {'item_id': '47700',
  'item_name': 'Command and Conquer 4: Tiberian Twilight',
  'playtime_forever': 85,
  'playtime_2weeks': 0},
 {'item_id': '24960',
  'item_name': 'Battlefield: Bad Company 2',
  'playtime_forever': 5716,
  'playtime_2weeks': 0},
 {'item_id': '43110',
  'item_name': 'Metro 2033',
  'playtime_forever': 834,
  'playtime_2weeks': 0},
 {'item_id': '8190',
  'item_name': 'Just Cause 2',
  'playtime_forever': 3083,
  'playtime_2weeks': 0},
 {'item_id': '49600',
  'item_name': 'Beat Hazard',
  'playtime_forever': 127,
  'playtime_2weeks': 0},
 {'item_id': '31220',
  'item_name': 'Sam & Max 301: The Penal Zone',
  'playtime_forever': 71,
  'playtime_2weeks': 0},
 {'item_id': '31230',
  'item_name': 'Sam & Max 302: The Tomb of Sammun-Mak',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '31240',
  'item_name': "Sam & Max 303: They Stole Max's Brain!",
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '31250',
  'item_name': 'Sam & Max 304: Beyond the Alley of the Dolls',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '31260',
  'item_name': 'Sam & Max 305: The City that Dares not Sleep',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '21090',
  'item_name': 'F.E.A.R.',
  'playtime_forever': 585,
  'playtime_2weeks': 0},
 {'item_id': '21110',
  'item_name': 'F.E.A.R.: Extraction Point',
  'playtime_forever': 146,
  'playtime_2weeks': 0},
 {'item_id': '21120',
  'item_name': 'F.E.A.R.: Perseus Mandate',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '49400',
  'item_name': 'Magic: The Gathering - Duels of the Planeswalkers',
  'playtime_forever': 32,
  'playtime_2weeks': 0},
 {'item_id': '33910',
  'item_name': 'Arma 2',
  'playtime_forever': 3,
  'playtime_2weeks': 0},
 {'item_id': '33930',
  'item_name': 'Arma 2: Operation Arrowhead',
  'playtime_forever': 3,
  'playtime_2weeks': 0},
 {'item_id': '219540',
  'item_name': 'Arma 2: Operation Arrowhead Beta (Obsolete)',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '17410',
  'item_name': "Mirror's Edge",
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '205790',
  'item_name': 'Dota 2 Test',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '50130',
  'item_name': 'Mafia II',
  'playtime_forever': 707,
  'playtime_2weeks': 0},
 {'item_id': '62100',
  'item_name': 'Chime',
  'playtime_forever': 50,
  'playtime_2weeks': 0},
 {'item_id': '31280',
  'item_name': 'Poker Night at the Inventory',
  'playtime_forever': 206,
  'playtime_2weeks': 0},
 {'item_id': '57300',
  'item_name': 'Amnesia: The Dark Descent',
  'playtime_forever': 12,
  'playtime_2weeks': 0},
 {'item_id': '21970',
  'item_name': 'R.U.S.E',
  'playtime_forever': 64,
  'playtime_2weeks': 0},
 {'item_id': '8930',
  'item_name': "Sid Meier's Civilization V",
  'playtime_forever': 10345,
  'playtime_2weeks': 0},
 {'item_id': '41000',
  'item_name': 'Serious Sam HD: The First Encounter',
  'playtime_forever': 369,
  'playtime_2weeks': 0},
 {'item_id': '41050',
  'item_name': 'Serious Sam Classic: The First Encounter',
  'playtime_forever': 76,
  'playtime_2weeks': 0},
 {'item_id': '41060',
  'item_name': 'Serious Sam Classic: The Second Encounter',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '227780',
  'item_name': 'Serious Sam Classics: Revolution',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '18040',
  'item_name': 'DeathSpank',
  'playtime_forever': 594,
  'playtime_2weeks': 0},
 {'item_id': '22380',
  'item_name': 'Fallout: New Vegas',
  'playtime_forever': 43,
  'playtime_2weeks': 0},
 {'item_id': '42700',
  'item_name': 'Call of Duty: Black Ops',
  'playtime_forever': 966,
  'playtime_2weeks': 0},
 {'item_id': '42710',
  'item_name': 'Call of Duty: Black Ops - Multiplayer',
  'playtime_forever': 2452,
  'playtime_2weeks': 0},
 {'item_id': '62000',
  'item_name': 'Flight Control HD',
  'playtime_forever': 25,
  'playtime_2weeks': 0},
 {'item_id': '40800',
  'item_name': 'Super Meat Boy',
  'playtime_forever': 119,
  'playtime_2weeks': 0},
 {'item_id': '9500',
  'item_name': 'Gish',
  'playtime_forever': 6,
  'playtime_2weeks': 0},
 {'item_id': '18700',
  'item_name': 'And Yet It Moves',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '31270',
  'item_name': 'Puzzle Agent',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '58200',
  'item_name': 'Jolly Rover',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '70400',
  'item_name': "Recettear: An Item Shop's Tale",
  'playtime_forever': 537,
  'playtime_2weeks': 0},
 {'item_id': '41300',
  'item_name': 'Altitude',
  'playtime_forever': 50,
  'playtime_2weeks': 0},
 {'item_id': '41800',
  'item_name': 'Gratuitous Space Battles',
  'playtime_forever': 149,
  'playtime_2weeks': 0},
 {'item_id': '42500',
  'item_name': 'DogFighter',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '49900',
  'item_name': 'Plain Sight',
  'playtime_forever': 23,
  'playtime_2weeks': 0},
 {'item_id': '55000',
  'item_name': 'Flotilla',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '34330',
  'item_name': 'Total War: SHOGUN 2',
  'playtime_forever': 1538,
  'playtime_2weeks': 0},
 {'item_id': '63200',
  'item_name': 'Monday Night Combat',
  'playtime_forever': 573,
  'playtime_2weeks': 0},
 {'item_id': '99810',
  'item_name': 'Bulletstorm',
  'playtime_forever': 2,
  'playtime_2weeks': 0},
 {'item_id': '620',
  'item_name': 'Portal 2',
  'playtime_forever': 887,
  'playtime_2weeks': 0},
 {'item_id': '42910',
  'item_name': 'Magicka',
  'playtime_forever': 588,
  'playtime_2weeks': 0},
 {'item_id': '15500',
  'item_name': 'The Wonderful End of the World',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '15540',
  'item_name': '1... 2... 3... KICK IT! (Drop That Beat Like an Ugly Baby)',
  'playtime_forever': 4,
  'playtime_2weeks': 0},
 {'item_id': '18500',
  'item_name': 'Defense Grid: The Awakening',
  'playtime_forever': 126,
  'playtime_2weeks': 0},
 {'item_id': '26500',
  'item_name': 'Cogs',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '35460',
  'item_name': 'The Ball',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '38700',
  'item_name': 'Toki Tori',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '38720',
  'item_name': 'RUSH',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '63700',
  'item_name': 'BIT.TRIP BEAT',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '280',
  'item_name': 'Half-Life: Source',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '20920',
  'item_name': 'The Witcher 2: Assassins of Kings Enhanced Edition',
  'playtime_forever': 1343,
  'playtime_2weeks': 0},
 {'item_id': '105600',
  'item_name': 'Terraria',
  'playtime_forever': 772,
  'playtime_2weeks': 0},
 {'item_id': '98200',
  'item_name': 'Frozen Synapse',
  'playtime_forever': 9,
  'playtime_2weeks': 0},
 {'item_id': '4500',
  'item_name': 'S.T.A.L.K.E.R.: Shadow of Chernobyl',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '4540',
  'item_name': 'Titan Quest',
  'playtime_forever': 3,
  'playtime_2weeks': 0},
 {'item_id': '4550',
  'item_name': 'Titan Quest: Immortal Throne',
  'playtime_forever': 76,
  'playtime_2weeks': 0},
 {'item_id': '9480',
  'item_name': 'Saints Row 2',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '15620',
  'item_name': 'Warhammer¬Æ 40,000‚Ñ¢: Dawn of War¬Æ II',
  'playtime_forever': 2085,
  'playtime_2weeks': 0},
 {'item_id': '20500',
  'item_name': 'Red Faction: Guerrilla Steam Edition',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '20570',
  'item_name': 'Warhammer¬Æ 40,000‚Ñ¢: Dawn of War¬Æ II - Chaos Rising‚Ñ¢',
  'playtime_forever': 69,
  'playtime_2weeks': 0},
 {'item_id': '50620',
  'item_name': 'Darksiders',
  'playtime_forever': 101,
  'playtime_2weeks': 0},
 {'item_id': '55100',
  'item_name': 'Homefront',
  'playtime_forever': 51,
  'playtime_2weeks': 0},
 {'item_id': '55140',
  'item_name': 'MX vs. ATV Reflex',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '56400',
  'item_name': 'Warhammer¬Æ 40,000‚Ñ¢: Dawn of War¬Æ II ‚Äì Retribution‚Ñ¢',
  'playtime_forever': 678,
  'playtime_2weeks': 0},
 {'item_id': '475150',
  'item_name': 'Titan Quest Anniversary Edition',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '96100',
  'item_name': 'Defy Gravity',
  'playtime_forever': 9,
  'playtime_2weeks': 0},
 {'item_id': '35450',
  'item_name': 'Rising Storm/Red Orchestra 2 Multiplayer',
  'playtime_forever': 14194,
  'playtime_2weeks': 0},
 {'item_id': '236830',
  'item_name': 'Red Orchestra 2: Heroes of Stalingrad - Single Player',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '72850',
  'item_name': 'The Elder Scrolls V: Skyrim',
  'playtime_forever': 2512,
  'playtime_2weeks': 0},
 {'item_id': '107100',
  'item_name': 'Bastion',
  'playtime_forever': 640,
  'playtime_2weeks': 0},
 {'item_id': '57690',
  'item_name': 'Tropico 4',
  'playtime_forever': 1815,
  'playtime_2weeks': 0},
 {'item_id': '91310',
  'item_name': 'Dead Island',
  'playtime_forever': 2078,
  'playtime_2weeks': 0},
 {'item_id': '113200',
  'item_name': 'The Binding of Isaac',
  'playtime_forever': 1494,
  'playtime_2weeks': 0},
 {'item_id': '65800',
  'item_name': 'Dungeon Defenders',
  'playtime_forever': 130,
  'playtime_2weeks': 0},
 {'item_id': '9200',
  'item_name': 'RAGE',
  'playtime_forever': 653,
  'playtime_2weeks': 0},
 {'item_id': '41070',
  'item_name': 'Serious Sam 3: BFE',
  'playtime_forever': 716,
  'playtime_2weeks': 0},
 {'item_id': '48950',
  'item_name': 'Greed Corp',
  'playtime_forever': 72,
  'playtime_2weeks': 0},
 {'item_id': '92800',
  'item_name': 'SpaceChem',
  'playtime_forever': 262,
  'playtime_2weeks': 0},
 {'item_id': '104700',
  'item_name': 'Super Monday Night Combat',
  'playtime_forever': 44,
  'playtime_2weeks': 0},
 {'item_id': '203770',
  'item_name': 'Crusader Kings II',
  'playtime_forever': 18,
  'playtime_2weeks': 0},
 {'item_id': '203810',
  'item_name': 'Dear Esther',
  'playtime_forever': 86,
  'playtime_2weeks': 0},
 {'item_id': '110800',
  'item_name': 'L.A. Noire',
  'playtime_forever': 1204,
  'playtime_2weeks': 0},
 {'item_id': '207610',
  'item_name': 'The Walking Dead',
  'playtime_forever': 798,
  'playtime_2weeks': 0},
 {'item_id': '98300',
  'item_name': 'Toy Soldiers',
  'playtime_forever': 110,
  'playtime_2weeks': 0},
 {'item_id': '50300',
  'item_name': 'Spec Ops: The Line',
  'playtime_forever': 296,
  'playtime_2weeks': 0},
 {'item_id': '204300',
  'item_name': 'Awesomenauts',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '1700',
  'item_name': 'Arx Fatalis',
  'playtime_forever': 0,
  'playtime_2weeks': 0},
 {'item_id': '205100',
  'item_name': 'Dishonored',
  'playtime_forever': 1429,
  'playtime_2weeks': 0},
 {'item_id': '211120',
  'item_name': 'The Political Machine',
  'playtime_forever': 1,

In [58]:
# En la La columna items esta compuesta de dicconarios por lo que se procede a normalziar de forma de obtener una columna por cada clave de ese diccionario
df_items = pd.json_normalize(data, record_path=['items'], meta=['steam_id','items_count','user_id', 'user_url'] )
df_items

,item_id,item_name,playtime_forever,playtime_2weeks,steam_id,items_count,user_id,user_url
0,10,Counter-Strike,6,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
1,20,Team Fortress Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
2,30,Day of Defeat,7,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
3,40,Deathmatch Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
4,50,Half-Life: Opposing Force,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
...,...,...,...,...,...,...,...,...
5153204,346330,BrainBread 2,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153205,373330,All Is Dust,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153206,388490,One Way To Die: Steam Edition,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153207,521570,You Have 10 Seconds 2,4,4,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153208,519140,Minds Eyes,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...

In [59]:
# Revisamos las columnas
df_items.columns

Index(['item_id', 'item_name', 'playtime_forever', 'playtime_2weeks',
       'steam_id', 'items_count', 'user_id', 'user_url'],
      dtype='object')

In [63]:
# Solo requerimos las columnas usser_id y items
df_items.drop(columns=['item_name', 'playtime_2weeks',  'steam_id', 'items_count', 'user_url'], inplace=True)

In [64]:
# Verificamos los cambios, nos falta el a√±o, el genero y el nombre del usuario
df_items

        item_id  playtime_forever            user_id
0            10                 6  76561197970982479
1            20                 0  76561197970982479
2            30                 7  76561197970982479
3            40                 0  76561197970982479
4            50                 0  76561197970982479
...         ...               ...                ...
5153204  346330                 0  76561198329548331
5153205  373330                 0  76561198329548331
5153206  388490                 3  76561198329548331
5153207  521570                 4  76561198329548331
5153208  519140                 3  76561198329548331

[5153209 rows x 3 columns]

In [111]:
# Revisar columnas
df_items.columns

Index(['genres', 'id', 'year'], dtype='object')

In [136]:
merged_df = pd.merge(df_items, df_items_reviews, how='inner')

In [137]:
merged_df

           genres  early_access        id  year
0          Action           0.0  761140.0  2018
1          Casual           0.0  761140.0  2018
2           Indie           0.0  761140.0  2018
3      Simulation           0.0  761140.0  2018
4        Strategy           0.0  761140.0  2018
...           ...           ...       ...   ...
74831      Racing           0.0  610660.0  2018
74832  Simulation           0.0  610660.0  2018
74833      Casual           0.0  658870.0  2017
74834       Indie           0.0  658870.0  2017
74835        None           1.0  681550.0  2016

[74836 rows x 4 columns]

In [145]:
filtered_df = merged_df[merged_df['early_access'] == 0]
print(filtered_df)

Empty DataFrame
Columns: [genres, early_access, id, year]
Index: []

In [144]:
# Eliminar las filas donde early_access es igual a 0
merged_df = merged_df.drop(merged_df[merged_df['early_access'] == 0].index)

In [146]:
# Revisamos la data
merged_df

             genres  early_access        id  year
37           Action           1.0  768570.0  2016
38            Indie           1.0  768570.0  2016
39       Simulation           1.0  768570.0  2016
40     Early Access           1.0  768570.0  2016
70             None           1.0  772590.0  2016
...             ...           ...       ...   ...
74804         Indie           1.0  772180.0  2016
74805    Simulation           1.0  772180.0  2016
74806        Sports           1.0  772180.0  2016
74807  Early Access           1.0  772180.0  2016
74835          None           1.0  681550.0  2016

[6503 rows x 4 columns]

In [148]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6503 entries, 37 to 74835
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   genres        6018 non-null   object
 1   early_access  6503 non-null   float64
 2   id            6503 non-null   float64
 3   year          6503 non-null   int32
dtypes: float64(2), int32(1), object(1)
memory usage: 228.6+ KB

In [152]:
# Se guarda esta data para el uso de la api
merged_df.to_parquet('dataset/df_UserForGenre.parquet', engine='pyarrow')

In [149]:
# Revisemos las columnas
merged_df.columns

Index(['genres', 'early_access', 'id', 'year'], dtype='object')

In [153]:
# implementemos el codigo para la API
genero='Simulation'

 # Filtrar el DataFrame por el g√©nero dado
genre_df = merged_df[merged_df['genres'] == genero]

# Si el DataFrame filtrado est√° vac√≠o, retornar el formato esperado con valores nulos
if genre_df.empty:
    print( {"Usuario con m√°s horas jugadas para G√©nero " + genero: None, "Horas jugadas": []})

# Agrupar por usuario y sumar las horas jugadas
user_hours = genre_df.groupby('id')['early_access'].sum()

# Encontrar el usuario con m√°s horas jugadas
max_user = user_hours.idxmax()

# Agrupar por a√±o y sumar las horas jugadas
year_hours = genre_df.groupby('year')['early_access'].sum().reset_index()

# Formatear el resultado en la estructura solicitada
hours_per_year = [{"A√±o": row['year'], "Horas": row['early_access']} for _, row in year_hours.iterrows()]

result = {
    "Usuario con m√°s horas jugadas para G√©nero " + genero: max_user,
    "Horas jugadas": hours_per_year
}

print(result)

{'Usuario con m√°s horas jugadas para G√©nero Simulation': 108600.0, 'Horas jugadas': [{'A√±o': 2001.0, 'Horas': 1.0}, {'A√±o': 2012.0, 'Horas': 1.0}, {'A√±o': 2013.0, 'Horas': 4.0}, {'A√±o': 2014.0, 'Horas': 20.0}, {'A√±o': 2015.0, 'Horas': 63.0}, {'A√±o': 2016.0, 'Horas': 118.0}, {'A√±o': 2017.0, 'Horas': 183.0}, {'A√±o': 2018.0, 'Horas': 8.0}]}